titles_from_headings:
  collections: true
excerpt_separator: "\n\n\n"
exclude:
  - LICENSE
  - README.md
  - .ruby-lsp
url: "https://dgck81lnn.github.io"
baseurl: /blog

title: LNN的博客！
permalink: "posts/:short_year:month:day_:title"
lang: zh_CN
author:
  name: DGCK81LNN
  url: "https://github.com/DGCK81LNN"

collections:
  diary_entries: { }
  tags: { }

defaults:
- scope:
    path: ""
    type: posts
  values:
    layout: posts
    soulblog-comments: true
- scope:
    path: pages
  values:
    layout: default
    seo:
      type: WebPage
    soulblog-header-tab: none
- scope:
    path: diary
  values:
    soulblog-breadcrumb:
    - text: '我的日记存档'
      href: '/blog/diary/'
    soulblog-header-tab: none
- scope:
    path: diary/index.md
  values:
    soulblog-breadcrumb: []

kramdown:
  math_engine: katex
