titles_from_headings:
  collections: true
excerpt_separator: "\n\n\n"
exclude:
  - LICENSE
  - README.md
baseurl: /blog

title: LNN的博客！
permalink: ":categories/posts/:short_year:month:day_:title"
locale: zh-CN
author:
  name: DGCK81LNN
  url: "https://github.com/DGCK81LNN"
soulblog-comment-url: "https://www.wjx.top/vm/rljkHbJ.aspx"

collections:
  diary_entries: { }
defaults:
- scope: { type: "posts" }
  values:
    layout: default
- scope: { path: "diary" }
  values:
    soulblog-breadcrumb:
    - { text: '我的日记存档', href: '/blog/diary/' }
- scope: { path: "_diary_entries/lnnsdiary" }
  values:
    category: lnnsdiary
- scope: { path: "_diary_entries/loose" }
  values:
    category: loose
- scope: { path: "_diary_entries/diarytxt" }
  values:
    category: diarytxt
