baseurl: /blog
title: LNN的博客！
plugins:
  - jekyll-seo-tag
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter
  - jekyll-redirect-from
  - jekyll-textile-converter
titles_from_headings:
  collections: true
exclude:
  - LICENSE
  - README.md
  - package-lock.json
excerpt_separator: "\n\n\n"
defaults:
- scope: { type: "posts" }
  values:
    layout: default
- scope: { path: "diary", type: "posts" }
  values:
    published: false
    excerpt: ""
    soulblog-breadcrumb:
    - { href: "/blog/diary", text: "LNN's Diary" }
