titles_from_headings:
  collections: true
excerpt_separator: "\n\n\n"
exclude:
  - LICENSE
  - README.md
url: "https://dgck81lnn.github.io"
baseurl: /blog

title: LNN的博客！
permalink: "posts/:short_year:month:day_:title"
lang: zh_CN
author:
  name: DGCK81LNN
  url: "https://github.com/DGCK81LNN"
soulblog-comment-url: "https://www.wjx.top/vm/rljkHbJ.aspx"

collections:
  diary_entries: { }
  tag_descriptions: { }
  pages_:
    output: true
    permalink: "pages/:path"

defaults:
- scope: { type: "posts" }
  values:
    layout: posts
- scope: { type: "pages_" }
  values:
    layout: default
    seo:
      type: WebPage
- scope: { path: "diary" }
  values:
    soulblog-breadcrumb:
    - text: '我的日记存档'
      href: '/blog/diary/'
- scope: { type: "tag_pages" }
  values:
    layout: default
    permalink: "tags/:slug"
