titles_from_headings:
  collections: true
exclude:
  - LICENSE
  - README.md
excerpt_separator: "\n\n\n"

baseurl: /blog
title: LNN的博客！
locale: zh-CN
author:
  name: DGCK81LNN
  url: "https://github.com/DGCK81LNN"

collections:
- diary_entries
defaults:
- scope: { type: "posts" }
  values:
    layout: default
